### ISSUE TITLE
feat: onnxruntime wasm support + example

### ISSUE THREAD

**Issue by mosure** [pykeio/ort#175]
https://onnxruntime.ai/docs/build/web.html

a native/web symmetric wrapper API would be really neat

**Comment by decahedron1** [comment]
WASM is supported since v1.15.5. https://ort.pyke.io/setup/platforms

The existing `gpt2` & `custom-ops` examples work in WASM (the others use `show-image` which isn't supported in WASM, but you can just remove that, the inference part works fine). I believe you need to disable the `fetch-models` feature and refactor `commit_from_url` -> `commit_from_file` though.
