### ISSUE TITLE
support x86_64-pc-windows-gnu

### ISSUE THREAD

**Issue by lucidfrontier45** [pykeio/ort#189]
Hi. I want to ask if support for x86_64-pc-windows-gnu target is possible or not.
Is binary building handled in this repo? https://github.com/pykeio/onnxruntime-build

**Comment by decahedron1** [comment]
Unfortunately, I don't think ONNX Runtime supports MinGW, so that would be a no (for out-of-the-box `ort`).

You could build ONNX Runtime from source (with MSVC) as a dynamic library, and [configure `ort` to use dynamic linking](https://ort.pyke.io/setup/linking#dynamic-linking). I don't believe there would be any ABI issues there.
