### ISSUE TITLE
 (exit code: 0xc0000139, STATUS_ENTRYPOINT_NOT_FOUND)

### ISSUE THREAD

**Issue by 86maid** [pykeio/ort#222]
After I compile successfully, run panic.
I am an X64 system, using static compilation

**Comment by decahedron1** [comment]
OS version? Any chance you can make a minimal repro?

**Comment by 86maid** [comment]
The version is Windows 10, 1909.

I'm sorry I can't provide you with a minimal repro because it runs fine on my machine, but a panic occurs on a specific client machine. Below is the link to my project:

https://github.com/86maid/ddddocr/

What I know is that the panic is related to loading the link library, as Windows popped up an error window.

![4cfff0fc4fa80db2a571c618396932d8](https://github.com/pykeio/ort/assets/134382214/ced2dac9-0b3d-4ba2-843d-54ed6baba5bd)

I am using static linking, and I don't know why this is happening.

**Comment by decahedron1** [comment]
`ort` binaries are built with the DirectML execution provider by default. This error is occurring because it cannot find `DirectML.dll` (actually, DML started shipping with 1903, so it's probably just outdated).

To support older versions of Windows 10, ship the DirectML.dll from [here](https://www.nuget.org/packages/Microsoft.AI.DirectML/) alongside your application. This is required for the default binaries even if you don't use the DML provider. The other option is to build ONNX Runtime from source without the DirectML EP.
