### ISSUE TITLE
Segfault on Silero v5

### ISSUE THREAD

**Issue by blueridanus** [pykeio/ort#274]
Steps to reproduce:
```
git clone https://github.com/emotechlab/silero-rs
cd silero-rs
git checkout silero-v5
cargo test --all-features
```
Context:
https://github.com/emotechlab/silero-rs/pull/14

![360981192-46e19e0e-ab9e-4aa9-9796-79836bea6e1e](https://github.com/user-attachments/assets/a6df26ee-7cdc-41fd-82a7-cbaa0495d164)

Reproduced on `2.0.0-rc.4`, `2.0.0-rc.5` and main ([bc70a0a](https://github.com/pykeio/ort/commit/bc70a0aa4b1af2036f23b77b3409da9bb2708643)).

[Link to Silero v5 onnx model](https://github.com/snakers4/silero-vad/blob/46f94b7d6029e19b482eebdfff0c18012fa84675/src/silero_vad/data/silero_vad.onnx)

**Comment by blueridanus** [comment]
I'm guessing probably coming from some tensor size mismatch, loading the session works. Will add details once I find out what's triggering the segfault.

**Comment by decahedron1** [comment]
https://github.com/emotechlab/silero-rs/blob/f5e00506d7a96f1c9be59fdb678c70694c3be4b8/src/lib.rs#L163-L168

The model only takes 3 inputs: `input`, `state`, and `sr`. Here, 4 inputs are provided (I believe `h` and `c` need to be concatenated on the last axis). I must've missed something in `ort` so that it doesn't see a problem there, thus ONNX Runtime sees 4 inputs but 3 input names, triggering the segfault.
