### ISSUE TITLE
CoreML only enable CPU and GPU

### ISSUE THREAD

**Issue by moritzsur** [pykeio/ort#310]
When using CoreML in swift, I am able to choose between four processing options:
- cpu only
- cpu and gpu
- cpu and neural engine
- all

example:
```
let configuration = MLModelConfiguration()
configuration.computeUnits = .cpuAndGPU
```

Choosing the cpu and gpu only option sped up inference for our model a lot, but I could only find the cpu only option in the crates coreml provider options: `use_cpu_only `.

Is there another way to set exectution provider options?

(Rust newbie here)

**Comment by audioXD** [comment]
The issue seems to be that `onnxruntime` doesn’t expose this functionality, or at least it’s not documented yet.
[https://onnxruntime.ai/docs/execution-providers/CoreML-ExecutionProvider.html#available-options](https://onnxruntime.ai/docs/execution-providers/CoreML-ExecutionProvider.html#available-options)
