### ISSUE TITLE
Use prebuild msvc binaries for windows-gnu

### ISSUE THREAD

**Issue by andrejohansson** [pykeio/ort#331]
Can I download and use the msvc binaries when building for `x86_64-pc-windows-gnu`?

Eg can I download this and use when building?
https://github.com/pykeio/ort/blob/main/ort-sys/dist.txt#L9

If so, then how, where is the expected location of this binary, is some env var pointing to it?

**Comment by decahedron1** [comment]
You cannot use the MSVC binaries for a `-gnu` target because the ABIs are incompatible. You'll have to compile ONNX Runtime from source, though I'm not sure if GNU ABI on Windows is supported. If you do get that working, see here for how to configure ort to link to custom binaries: https://ort.pyke.io/setup/linking
