### ISSUE TITLE
Document EnvBuilder::with_global_thread_pool

### ISSUE THREAD

**Issue by mush42** [pykeio/ort#56]
Hi,

The signature of `EnvBuilder::with_global_thread_pool` is as follows:

```
pub fn with_global_thread_pool(self, options: Vec<(String, String)>) -> EnvBuilder
```

What value the `options` arguments is expected to contain?

Best
Musharraf

**Comment by CeNiEi** [comment]
@mush42 Hello, I had the same problems, and i was able to get what i wanted after looking at the source code from [here](https://docs.rs/ort/latest/src/ort/environment.rs.html#52-55). Check out for the method `create_global_thread_pool_env`, inside it you will be able to see the variants. I have still listed them below for easy access. 

Apart from this i would also recommend keeping the api docs for onnx runtime close: https://onnxruntime.ai/docs/api/c/index.html

I am linking the api docs, so that you can look at what the possible values of each of these options are.

Here are the allowed variants: 
- [`intra_op_parallelism`](https://onnxruntime.ai/docs/api/c/struct_ort_api.html#a16f2b2e2a62d80725b3f7a39e9f49c07)
- [`inter_op_parallelism`](https://onnxruntime.ai/docs/api/c/struct_ort_api.html#a66522b73526d041a545b59eb2b46c851)
- [`spin_control`](https://onnxruntime.ai/docs/api/c/struct_ort_api.html#a39d4699e56ac6e887b2f9e69e6e8c946)
- [`intra_op_thread_affinity`](https://github.com/microsoft/onnxruntime/blob/68b5b2d7d33b6aa2d2b5cf8d89befb4a76e8e7d8/include/onnxruntime/core/session/onnxruntime_c_api.h#L3636): This one is a bit tricky, i have linked a code excerpt, which shows how to set thread affinities (I am Copy-Pasting the method from there): 
```
/*  \brief Set affinities for intra op threads
  *
  * Affinity string follows format:
  * logical_processor_id,logical_processor_id;logical_processor_id,logical_processor_id
  * Semicolon isolates configurations among threads, while comma split processors where ith thread expected to attach to.
  * e.g. 1,2,3;4,5
  * specifies affinities for two threads, with the 1st thread attach to the 1st, 2nd, and 3rd processor, and 2nd thread to the 4th and 5th.
  * To ease the configuration, an "interval" is also allowed:
  * e.g. 1-8;8-16;17-24
  * orders that the 1st thread runs on first eight processors, 2nd thread runs on next eight processors, and so forth.
  * Note:
  * 1. Once set, the number of thread affinities must equal to intra_op_num_threads - 1,
  *    ort does not set affinity on the main thread which is started and managed by the calling app;
  * 2. For windows, ort will infer the group id from a logical processor id, for example, assuming there are two groups with each has 64 logical processors,
  *    an id of 64 will be inferred as the last processor of the 1st group, while 65 will be interpreted as the 1st processor of the second group.
  *    Hence 64-65 is an invalid configuration, because a windows thread cannot be attached to processors across group boundary.
  * 
  *  \since Version 1.14
  */
```
I found this from [here](https://onnxruntime.ai/docs/performance/tune-performance/threading.html#set-intra-op-thread-affinity)

**Comment by mush42** [comment]
@CeNiEi  thanks.
